Fix error: cannot find symbol ChangeUtil.messageUUID(dbProvider.get()))
This change
https://github.com/gerrit-review/gerrit/commit/5a142312e9f83cf2a230263fbc1cafb838cf5940

broke that file because it renamed a variable.

Change-Id: Iffba7e0f9afae951fc58da6304d87ebbadeb4e55